name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - "frontend/**"
      - ".github/workflows/docker-publish.yml"

jobs:

  build-api:
    runs-on: ubuntu-latest
    name: Build & Push API

    if: |
      !contains(github.event.head_commit.message, '[skip-api]') &&
      (
        contains(join(github.event.commits.*.modified), 'api/') ||
        contains(join(github.event.commits.*.added), 'api/') ||
        contains(join(github.event.commits.*.removed), 'api/')
      )

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-td:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/api-td:${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest
    name: Build & Push FRONTEND

    needs: build-api

    if: |
      !contains(github.event.head_commit.message, '[skip-frontend]') &&
      (
        contains(join(github.event.commits.*.modified), 'frontend/') ||
        contains(join(github.event.commits.*.added), 'frontend/') ||
        contains(join(github.event.commits.*.removed), 'frontend/')
      )

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push FRONTEND
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend-td:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend-td:${{ github.sha }}
