name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-api:
    runs-on: ubuntu-latest
    name: Build & Push API
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check API changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'api/**'
      
      - name: Login to Docker Hub
        if: steps.filter.outputs.api == 'true' && !contains(github.event.head_commit.message, '[skip-api]')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push API
        if: steps.filter.outputs.api == 'true' && !contains(github.event.head_commit.message, '[skip-api]')
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-td:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/api-td:${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest
    name: Build & Push FRONTEND
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check Frontend changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
      
      - name: Login to Docker Hub
        if: steps.filter.outputs.frontend == 'true' && !contains(github.event.head_commit.message, '[skip-frontend]')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push FRONTEND
        if: steps.filter.outputs.frontend == 'true' && !contains(github.event.head_commit.message, '[skip-frontend]')
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend-td:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend-td:${{ github.sha }}